// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Models;

namespace barterserv.Migrations
{
    [DbContext(typeof(BarterContext))]
    [Migration("20210809223037_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("backend.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(10) CHARACTER SET utf8mb4")
                        .HasMaxLength(10);

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Aide à la personne"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Beauté bien être"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Bricolage"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Cours"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Loisirs"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Maison"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Mode"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "Travail"
                        },
                        new
                        {
                            CategoryId = 9,
                            Name = "Vacances"
                        },
                        new
                        {
                            CategoryId = 10,
                            Name = "Vehicule"
                        });
                });

            modelBuilder.Entity("backend.Models.Message", b =>
                {
                    b.Property<int>("MsgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("varchar(140) CHARACTER SET utf8mb4")
                        .HasMaxLength(140);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OfferLinkedToId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.HasKey("MsgId");

                    b.HasIndex("OfferLinkedToId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("backend.Models.Offer", b =>
                {
                    b.Property<int>("OfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.HasKey("OfferId");

                    b.HasIndex("AuthorId")
                        .IsUnique();

                    b.ToTable("Offers");

                    b.HasData(
                        new
                        {
                            OfferId = 1,
                            AuthorId = 1
                        },
                        new
                        {
                            OfferId = 2,
                            AuthorId = 2
                        },
                        new
                        {
                            OfferId = 3,
                            AuthorId = 3
                        },
                        new
                        {
                            OfferId = 4,
                            AuthorId = 4
                        },
                        new
                        {
                            OfferId = 5,
                            AuthorId = 5
                        },
                        new
                        {
                            OfferId = 6,
                            AuthorId = 6
                        },
                        new
                        {
                            OfferId = 7,
                            AuthorId = 7
                        },
                        new
                        {
                            OfferId = 8,
                            AuthorId = 8
                        });
                });

            modelBuilder.Entity("backend.Models.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoryLinkToId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRecherche")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("OfferLinkedtoServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ServiceId");

                    b.HasIndex("CategoryLinkToId");

                    b.HasIndex("OfferLinkedtoServiceId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            ServiceId = 1,
                            CategoryLinkToId = 2,
                            IsRecherche = true,
                            OfferLinkedtoServiceId = 8,
                            Title = "Massage"
                        },
                        new
                        {
                            ServiceId = 2,
                            CategoryLinkToId = 3,
                            IsRecherche = true,
                            OfferLinkedtoServiceId = 8,
                            Title = "Electricité"
                        },
                        new
                        {
                            ServiceId = 3,
                            CategoryLinkToId = 10,
                            IsRecherche = true,
                            OfferLinkedtoServiceId = 8,
                            Title = "Entretien"
                        },
                        new
                        {
                            ServiceId = 4,
                            CategoryLinkToId = 4,
                            IsRecherche = true,
                            OfferLinkedtoServiceId = 8,
                            Title = "cours dotnet"
                        },
                        new
                        {
                            ServiceId = 5,
                            CategoryLinkToId = 6,
                            IsRecherche = false,
                            OfferLinkedtoServiceId = 8,
                            Title = "Jardinage"
                        },
                        new
                        {
                            ServiceId = 6,
                            CategoryLinkToId = 10,
                            IsRecherche = false,
                            OfferLinkedtoServiceId = 8,
                            Title = "Co Voiturage"
                        },
                        new
                        {
                            ServiceId = 7,
                            CategoryLinkToId = 9,
                            IsRecherche = false,
                            OfferLinkedtoServiceId = 8,
                            Title = "Hébergement"
                        });
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("varchar(30) CHARACTER SET utf8mb4")
                        .HasMaxLength(30);

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("varchar(30) CHARACTER SET utf8mb4")
                        .HasMaxLength(30);

                    b.Property<int>("Province")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Sexe")
                        .HasColumnType("int");

                    b.Property<int>("TimeCredit")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "ben@gmail.com",
                            Fullname = "Penelle",
                            Nickname = "Ben",
                            Province = 3,
                            Role = 0,
                            Sexe = 1,
                            TimeCredit = 5
                        },
                        new
                        {
                            UserId = 2,
                            Email = "bruno@gmail.com",
                            Fullname = "Lacroix",
                            Nickname = "Bru",
                            Province = 0,
                            Role = 0,
                            Sexe = 1,
                            TimeCredit = 5
                        },
                        new
                        {
                            UserId = 3,
                            Email = "aela@gmail.com",
                            Fullname = "Izere",
                            Nickname = "Aela",
                            Province = 8,
                            Role = 0,
                            Sexe = 0,
                            TimeCredit = 5
                        },
                        new
                        {
                            UserId = 4,
                            Email = "luis@gmail.com",
                            Fullname = "Save Lara",
                            Nickname = "Luis",
                            Province = 0,
                            Role = 0,
                            Sexe = 1,
                            TimeCredit = 5
                        },
                        new
                        {
                            UserId = 5,
                            Email = "amin@gmail.com",
                            Fullname = "Gandouz",
                            Nickname = "Amin",
                            Province = 0,
                            Role = 0,
                            Sexe = 1,
                            TimeCredit = 5
                        },
                        new
                        {
                            UserId = 6,
                            Email = "nico@gmail.com",
                            Fullname = "Krstev",
                            Nickname = "Nico",
                            Province = 1,
                            Role = 0,
                            Sexe = 1,
                            TimeCredit = 5
                        },
                        new
                        {
                            UserId = 7,
                            Email = "momo@gmail.com",
                            Fullname = "Mohammed Assbai",
                            Nickname = "Momo",
                            Province = 0,
                            Role = 0,
                            Sexe = 1,
                            TimeCredit = 5
                        },
                        new
                        {
                            UserId = 8,
                            Email = "bizidudu@gmail.com",
                            Fullname = "Olivier Bizimungu",
                            Nickname = "L'Olive",
                            Province = 8,
                            Role = 0,
                            Sexe = 1,
                            TimeCredit = 50
                        },
                        new
                        {
                            UserId = 9,
                            Email = "alain@gmail.com",
                            Fullname = "Alain Silovy",
                            Nickname = "Timon",
                            Province = 0,
                            Role = 0,
                            Sexe = 1,
                            TimeCredit = 5
                        });
                });

            modelBuilder.Entity("backend.Models.Message", b =>
                {
                    b.HasOne("backend.Models.Offer", "OfferLinkedTo")
                        .WithMany("AllCommunications")
                        .HasForeignKey("OfferLinkedToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Models.Offer", b =>
                {
                    b.HasOne("backend.Models.User", "Author")
                        .WithOne("OwnerOffer")
                        .HasForeignKey("backend.Models.Offer", "AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Models.Service", b =>
                {
                    b.HasOne("backend.Models.Category", "CategoryLinkTo")
                        .WithMany("CategorysServices")
                        .HasForeignKey("CategoryLinkToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Offer", "OfferLinkedtoService")
                        .WithMany("ServicesLinkedToOffer")
                        .HasForeignKey("OfferLinkedtoServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
